
networks:
  pratilib.net:
    driver: bridge
services:

  # service prati.app : gestion des praticiens construite avec Doctrine
  #
  prati.app:
#   image: 'canals/php:8.3-cli'
    build:
      context: build
      dockerfile: 8.3-cli.Dockerfile
    env_file: ./prat.env
    ports:
      - '3080:80'
    volumes:
      - .:/var/php
    working_dir: /var/php/
    networks:
      - pratilib.net
    depends_on:
      - praticien.db
    command: php -S 0.0.0.0:80 -t /var/php/public


  # service sql pour la base praticiens -
  #
  praticien.db:
    image: 'postgres:latest'
    env_file: ./prat.env
    ports:
      - '5432:5432'
    networks:
      - pratilib.net
    volumes:
      - ./sql:/var/sql
  #
  # service administration des bases sql
  #
  adminer:
    image: adminer
    ports:
      - '8080:8080'
    networks:
      - pratilib.net

